### PR TITLE
Fix formatting of build uri in release notes

### LINKED ISSUE #84: Release notes URL not encoded
If you have a VSTS project whose name includes spaces, and you included release notes as part of the Create Octopus Deploy VSTS build step, then the release notes will contain an invalid URL and the markdown cannot be rendered correctly as markdown.

For example, if your project name is `A Project With Spaces` and you have a build like this: 
image

then you will end up with a release like this:
image

Notice the release notes: `Release created by Build [A Project With Spaces-CI #89](https://octopus-deploy-test.visualstudio.com/A Project With Spaces/build/index?a=summary&buildId=89) from the A Project With Spaces repository in Team Project A Project With Spaces`.

The link is not rendered correctly as a markdown link because the URL contains space characters from the project name. The raw markdown should instead be `Release created by Build [A Project With Spaces-CI #89](https://octopus-deploy-test.visualstudio.com/A%20Project%20With%20Spaces/build/index?a=summary&buildId=89) from the A Project With Spaces repository in Team Project A Project With Spaces`. That is, the project name should be a correctly encoded URL. If this were the case, then the URL would be rendered correctly as a link.

The release notes here are being supplied as markdown by the Octopus VSTS plugin, so this plugin should be responsible for supplying valid URLs.

### PR DESCRIPTION
**Pull request by ArturDorochowicz**
Fixes #84.

### CODE REVIEW

File: source/tasks/Utils/environment.ts [hunk 1]
```diff
@@ -49,7 +49,7 @@ export const getVstsEnvironmentVariables= () : VstsEnvironmentVariables =>{
 
 export const generateReleaseNotesContent = (environment: VstsEnvironmentVariables, linkedItemReleaseNote: string, customReleaseNotes: string) => {
     let notes: string = "Release created by ";
-    const buildUri = `${environment.teamCollectionUri}${environment.projectName}/_build/index?_a=summary&buildId=${environment.buildId}`;
+    const buildUri = `${environment.teamCollectionUri}${encoreURIComponent(environment.projectName)}/_build/index?_a=summary&buildId=${encodeURIComponent(environment.buildId)}`;
```
Comment (alfhenrik) [inline source/tasks/Utils/environment.ts]: `encoreURIComponent` should be `encodeURIComponent` and we don't need to encode the `buildId` as it is typed as a number.

**Comment by ArturDorochowicz** [comment]
Corrected the first issue - that's what happens when you edit via Github.

W.r.t. the other thing, what you're proposing wouldn't pass my code review. I'm leaving it as is. I don't want to think about whether it's needed or not. I don't want to require the next guy to think about it. Plain and simple, an encoding is required for going from a string to a query string value. Here you actually have one more conversion on top of it, from a number to string.
